"""id to uuid

Revision ID: 12e0dafb390c
Revises: 66f08286c192
Create Date: 2026-03-28 10:48:33.623422

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "12e0dafb390c"
down_revision: Union[str, Sequence[str], None] = "66f08286c192"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- 1. DROP FOREIGN KEYS FIRST ---
    # This prevents 'dependent object' errors
    op.drop_constraint("subjects_branch_id_fkey", "subjects", type_="foreignkey")
    op.drop_constraint(
        "video_resources_subject_id_fkey", "video_resources", type_="foreignkey"
    )

    # --- 2. ALTER BRANCHES ---
    # Drop the integer default/identity first
    op.execute("ALTER TABLE branches ALTER COLUMN id DROP DEFAULT")
    op.alter_column(
        "branches",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="id::text::uuid",
    )

    # --- 3. ALTER SUBJECTS ---
    op.execute("ALTER TABLE subjects ALTER COLUMN id DROP DEFAULT")
    op.alter_column(
        "subjects",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="id::text::uuid",
    )

    op.alter_column(
        "subjects",
        "branch_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="branch_id::text::uuid",
    )

    # --- 4. ALTER VIDEO_RESOURCES ---
    op.execute("ALTER TABLE video_resources ALTER COLUMN id DROP DEFAULT")
    op.alter_column(
        "video_resources",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="id::text::uuid",
    )

    op.alter_column(
        "video_resources",
        "subject_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="subject_id::text::uuid",
    )

    # --- 5. RE-CREATE FOREIGN KEYS ---
    op.create_foreign_key(
        "subjects_branch_id_fkey", "subjects", "branches", ["branch_id"], ["id"]
    )
    op.create_foreign_key(
        "video_resources_subject_id_fkey",
        "video_resources",
        "subjects",
        ["subject_id"],
        ["id"],
    )

    # Re-create indices if they were dropped
    op.create_index(op.f("ix_branches_id"), "branches", ["id"], unique=False)
    op.create_index(op.f("ix_subjects_id"), "subjects", ["id"], unique=False)
    op.create_index(
        op.f("ix_video_resources_id"), "video_resources", ["id"], unique=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_video_resources_id"), table_name="video_resources")
    op.alter_column(
        "video_resources",
        "subject_id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "video_resources",
        "id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_subjects_id"), table_name="subjects")
    op.alter_column(
        "subjects",
        "branch_id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "subjects",
        "id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_branches_id"), table_name="branches")
    op.alter_column(
        "branches",
        "id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
