"""new schema for test

Revision ID: 195b317c42b1
Revises: 335ffd29398e
Create Date: 2026-04-05 09:44:06.846899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '195b317c42b1'
down_revision: Union[str, Sequence[str], None] = '335ffd29398e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('option_text', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('questions', sa.Column('question_type', sa.Enum('MCQ', 'MSQ', 'NAT', name='questiontype'), nullable=False))
    op.add_column('questions', sa.Column('numerical_answer', sa.Float(), nullable=True))
    op.add_column('questions', sa.Column('tolerance', sa.Float(), nullable=True))
    op.drop_column('questions', 'option_d')
    op.drop_column('questions', 'option_a')
    op.drop_column('questions', 'option_c')
    op.drop_column('questions', 'option_b')
    op.drop_column('questions', 'correct_option')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('correct_option', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('option_b', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('option_c', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('option_a', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('option_d', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('questions', 'tolerance')
    op.drop_column('questions', 'numerical_answer')
    op.drop_column('questions', 'question_type')
    op.drop_table('options')
    # ### end Alembic commands ###
