"""added questions table

Revision ID: 335ffd29398e
Revises: c7f03915242e
Create Date: 2026-04-03 11:31:45.468282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '335ffd29398e'
down_revision: Union[str, Sequence[str], None] = 'c7f03915242e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('option_a', sa.String(), nullable=False),
    sa.Column('option_b', sa.String(), nullable=False),
    sa.Column('option_c', sa.String(), nullable=False),
    sa.Column('option_d', sa.String(), nullable=False),
    sa.Column('correct_option', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    # ### end Alembic commands ###
