"""initial schema

Revision ID: 66f08286c192
Revises: 
Create Date: 2026-03-28 10:23:21.795253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66f08286c192'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('branches_name_key'), 'branches', type_='unique')
    op.create_index(op.f('ix_branches_name'), 'branches', ['name'], unique=True)
    op.add_column('subjects', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=False)
    op.add_column('video_resources', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_video_resources_title'), 'video_resources', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_resources_title'), table_name='video_resources')
    op.drop_column('video_resources', 'is_deleted')
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_column('subjects', 'is_deleted')
    op.drop_index(op.f('ix_branches_name'), table_name='branches')
    op.create_unique_constraint(op.f('branches_name_key'), 'branches', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('branches', 'is_deleted')
    # ### end Alembic commands ###
