"""calculate score validation added

Revision ID: 750844a84b74
Revises: e3afe22e5d22
Create Date: 2026-04-05 11:20:41.548792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '750844a84b74'
down_revision: Union[str, Sequence[str], None] = 'e3afe22e5d22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('marks', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'marks')
    # ### end Alembic commands ###
