"""initial

Revision ID: 9eca89dba49f
Revises: 
Create Date: 2026-04-12 14:28:20.922442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eca89dba49f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.alter_column('tests', 'subject_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'tests', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.alter_column('tests', 'subject_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('tests', 'branch_id')
    # ### end Alembic commands ###
