"""remove unique from source_url

Revision ID: aad516a6cf20
Revises: 657bb622e86c
Create Date: 2026-05-16 12:13:09.757966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad516a6cf20'
down_revision: Union[str, Sequence[str], None] = '657bb622e86c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('updates_source_url_key'), 'updates', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('updates_source_url_key'), 'updates', ['source_url'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
